# Generated by Django 4.0.5 on 2022-06-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=5, verbose_name='Аббревиатура')),
                ('full_name', models.CharField(max_length=50, verbose_name='Название валюты')),
                ('usd_price', models.DecimalField(decimal_places=2, max_digits=10, max_length=10, verbose_name='Цена к доллару')),
                ('last_time_update', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
