# Generated by Django 4.0.5 on 2022-06-03 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_currencypairs_delete_currency'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CurrencyPairs',
            new_name='CurrencyPair',
        ),
    ]
